#!/usr/bin/env python3
"""Generate src/dkarchag.htm — the Tibetan table of contents at the front.

    python3 tools/dkarchag.py            write src/dkarchag.htm
    python3 tools/dkarchag.py --check    exit 1 if it would change

The page is derived from toc.ncx, so it can never disagree with the reading
system's own menu: every navPoint that points into the text becomes a row,
nested navPoints become indented rows, and the ཟུར་ཡིག divider becomes a group
heading. Front and back matter (cover, title page, key, English contents,
annotations, jewels, colophon) are listed in a short second list at the foot.

Each row carries the prayer's English gloss from toc1.htm as a hidden span;
toggle.js shows the glosses when the reader asks (class toc-gloss on <html>).

The NCX menu cannot be enlarged; this page scales with the reader's text
size, which is why it exists (Peter, 2026-09-17).
"""
import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

SRC = Path(__file__).resolve().parent.parent / "src"
OUT = SRC / "dkarchag.htm"
NS = {"n": "http://www.daisy.org/z3986/2005/ncx/"}
FRONT_BACK = {"cover.xhtml": "མདུན་ཤོག Cover", "OPS/titlepage.htm": "མཚན་བྱང་། Title page", "dkarchag.htm": None,
              "key.xhtml": "How to read this book", "toc1.htm": "Contents in English", "mchan.htm": "࿙ Annotations",
              "jewels.htm": "༼࿉༽ Jewel Jumps", "acknowledgements.htm": "པར་བྱང་། Colophon"}
LABEL = re.compile(r"^(.*?)\s*(\d+)?\s*$", re.S)


def glosses():
    """href -> English gloss, from the hand-kept English TOC."""
    t = (SRC / "toc1.htm").read_text(encoding="utf-8")
    out = {}
    for m in re.finditer(r'<dt[^>]*>.*?<a href="([^"]+)">.*?</dt>\s*<dd>(.*?)</dd>', t, re.S):
        g = re.sub(r"<[^>]+>", "", m.group(2)); g = " ".join(g.split())
        if g and g != "TODO":
            out[m.group(1)] = g
    return out


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;")


def rows():
    root = ET.parse(SRC / "toc.ncx").getroot()
    gl = glosses()
    body, tail = [], []

    def walk(np, depth):
        label = np.find("n:navLabel/n:text", NS).text or ""
        src = np.find("n:content", NS).get("src")
        file = src.split("#")[0]
        if file in FRONT_BACK:
            name = FRONT_BACK[file]
            if name:
                tail.append(f'    <li><a href="{src}">{esc(name)}</a></li>')
            return
        m = LABEL.match(label); title, page = m.group(1).strip(), (m.group(2) or "")
        if np.get("id", "").startswith("divider"):
            body.append(f'  <li class="group"><span class="title">{esc(title)}</span></li>')
        else:
            g = gl.get(src, "")
            gloss = f'<span class="gloss">{esc(g)}</span>' if g else ""
            # The <a> holds the bare title and nothing else: Apple Books builds
            # its contents panel from the page the OPF guide names as "toc" and
            # reads each link's own text — spans inside the link came out blank
            # (build 261, 2026-09-17). The page number stands beside the link.
            body.append(f'  <li class="d{depth}"><a href="{src}">{esc(title)}</a>'
                        f'<span class="pg">{page}</span>{gloss}</li>')
        for child in np.findall("n:navPoint", NS):
            walk(child, depth + 1)

    for np in root.find("n:navMap", NS).findall("n:navPoint", NS):
        walk(np, 1)
    return body, tail


def render():
    body, tail = rows()
    return f'''<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="bo">
<head>
  <title>དཀར་ཆག</title>
  <link type="text/css" rel="stylesheet" href="stylesheet.css"/>
  <script type="text/javascript" src="toggle.js"></script>
</head>
<body class="calibreBody dkarchag">
<!-- GENERATED by tools/dkarchag.py from toc.ncx and the glosses in toc1.htm — do not edit; re-run the tool. -->
<h1 class="dkartitle">༄༅། །དཀར་ཆག</h1>
<p class="dkarhint"><span xml:lang="en">The page numbers are the printed book's.</span></p>
<ul class="dkarlist">
{chr(10).join(body)}
</ul>
<ul class="dkartail">
{chr(10).join(tail)}
</ul>
<div class="prefs needsjs"><p xml:lang="en"><a id="tocGloss" class="switch" href="#tocGloss">Show English titles</a></p></div>
</body>
</html>
'''


def main(argv):
    new = render()
    old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if "--check" in argv:
        print("dkarchag.htm up to date" if new == old else "dkarchag.htm would change"); return 0 if new == old else 1
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.name}: {new.count('<li')} rows")


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]) or 0)
