#!/usr/bin/env python3
"""Build the Jewel Jumps page: every landing jewel in the book, in reading order.

    python3 tools/jewels.py            # (re)write src/jewels.htm, register it first in spine, NCX and TOC page
    python3 tools/jewels.py --check    # list what would be written, touch nothing

A jewel is a <span class="inlineAnchor"> (or inlineAnchorReturn) with an id in
an OPS/ document — the red ༼࿉༽ mark that other links land on. Each line of the
page is one link to such a jewel: the jewel mark, the jewel's own label if it
has one, the first six syllables of the text that follows, then the prayer it
sits in and, where the book states one, the printed page (the nearest page
number marker above it in the same document).

Re-run whenever jewels are added, moved or removed; the page is regenerated
from scratch, and the spine/NCX/TOC-page entries are added only if missing.
Report-only apart from those three files and src/jewels.htm. nav.py leaves
this page alone: it has no tocpage heading and its links are pre-stamped.
"""
import re, sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "src"
OUT = SRC / "jewels.htm"
SYLLABLES = 6

JEWEL = re.compile(r'<span\b(?=[^>]*\bclass="inlineAnchor(?:Return)?")(?=[^>]*\bid="([^"]+)")[^>]*>(.*?)</span>', re.S)
HEADING = re.compile(r'<h[1-6][^>]*\bclass="tocpage[12][^"]*"[^>]*>(.*?)</h[1-6]>', re.S)
PAGENO = re.compile(r'<span class="pageno">(\d+)</span>')
TAGS = re.compile(r'<[^>]+>')
SYL = re.compile(r'[^\s་།༔༑༴༈]+[་།༔༑]*')

def spine():
    opf = (SRC / "content.opf").read_text(encoding="utf-8")
    items = {}
    for tag in re.findall(r'<item\b[^>]*>', opf):
        a = dict(re.findall(r'(\w[\w:-]*)="([^"]*)"', tag))
        if 'id' in a and 'href' in a: items[a['id']] = a['href']
    return [items[i] for i in re.findall(r'<itemref idref="([^"]+)"', opf) if i in items]

def clean(html):
    t = TAGS.sub(' ', html)
    t = re.sub(r'&#8194;|&#8202;|&#160;|&#8239;|&nbsp;', ' ', t)
    return re.sub(r'\s+', ' ', t).strip()

def first_syllables(text, n=SYLLABLES):
    """slice the original text at the end of the n-th syllable, so spaces survive"""
    ms = list(SYL.finditer(text))
    if not ms: return ''
    cut = ms[min(n, len(ms)) - 1].end()
    return text[:cut].strip() + ('…' if len(ms) > n else '')

def collect():
    rows = []
    for rel in spine():
        if not rel.startswith('OPS/'): continue
        path = SRC / rel
        if not path.exists(): continue
        text = path.read_text(encoding='utf-8')
        text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
        heads = [(m.start(), clean(re.sub(r'<a [^>]*>.*?</a>|<a [^>]*/>', '', m.group(1), flags=re.S)).replace(' ', ' ')) for m in HEADING.finditer(text)]
        pages = [(m.start(), m.group(1)) for m in PAGENO.finditer(text)]
        for m in JEWEL.finditer(text):
            jid, label = m.group(1), clean(m.group(2))
            pos = m.start()
            prayer = next((h for p, h in reversed(heads) if p < pos), '')
            prayer = re.sub(r'\s*\d+\s*$', '', prayer)          # the page number rides inside the heading text
            page = next((pg for p, pg in reversed(pages) if p < pos), '')
            after = text[m.end():m.end() + 1500]
            after = re.sub(r'<a class="jump[^"]*"[^>]*>.*?</a>', '', after, flags=re.S)   # skip jump links that follow the jewel
            incipit = first_syllables(clean(after))
            rows.append(dict(file=rel, id=jid, label=label, incipit=incipit, prayer=prayer, page=page))
    return rows

def render(rows):
    lines = []
    for r in rows:
        lab = f'<span class="inlineAnchor">{r["label"]}</span>' if r['label'] else '<span class="inlineAnchor"></span>'
        pg = f' <span class="lpn">{r["page"]}</span>' if r['page'] else ''
        lines.append(f'<p class="jewelrow">{lab} <a class="jumpDown" href="{r["file"]}#{r["id"]}" data-scope="out">{r["incipit"]}{pg}</a>'
                     f'<span class="jewelprayer">{r["prayer"]}</span></p>')
    body = '\n'.join(lines)
    return f'''<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Jewel Jumps</title>
  <link type="text/css" rel="stylesheet" href="stylesheet.css"/>
</head>
<body class="calibreBody">
<!-- GENERATED by tools/jewels.py — do not edit; re-run the tool. -->
<h1 class="jewelstitle">Jewel Jumps</h1>
<p class="jewelsintro">Every landing point in the book, in reading order: the mark, the first words after it, the prayer it belongs to and, where the printed book states it, the page. Tap a line to go there.</p>
{body}
</body>
</html>
'''

def register():
    """spine: first after the cover; NCX: first navPoint; TOC page: first row. Idempotent."""
    opf_p = SRC / 'content.opf'; opf = opf_p.read_text(encoding='utf-8')
    if 'href="jewels.htm"' not in opf:
        opf = opf.replace('<item href="toc1.htm"', '<item href="jewels.htm" id="jewels" media-type="application/xhtml+xml"/>\n    <item href="toc1.htm"', 1)
        opf = opf.replace('    <itemref idref="titlepage1"/>\n', '    <itemref idref="titlepage1"/>\n    <itemref idref="jewels"/>\n', 1)
        opf_p.write_text(opf, encoding='utf-8')
    ncx_p = SRC / 'toc.ncx'; ncx = ncx_p.read_text(encoding='utf-8')
    if 'jewels.htm' not in ncx:
        ncx = ncx.replace('  <navMap>\n', '  <navMap>\n    <navPoint id="num_0" playOrder="0">\n      <navLabel>\n        <text>༼࿉༽ Jewel Jumps</text>\n      </navLabel>\n      <content src="jewels.htm"/>\n    </navPoint>\n', 1)
        k = [0]
        def renum(m):
            k[0] += 1; return f'<navPoint id="num_{k[0]}" playOrder="{k[0]}">'
        ncx = re.sub(r'<navPoint id="num_[^"]*" playOrder="\d+">', renum, ncx)
        ncx_p.write_text(ncx, encoding='utf-8')
    toc_p = SRC / 'toc1.htm'; toc = toc_p.read_text(encoding='utf-8')
    if 'jewels.htm' not in toc:
        toc = toc.replace('  <dl class="toctib1">\n', '  <dl class="toctib1">\n\n  <dt><a href="jewels.htm">༼࿉༽ Jewel Jumps</a></dt>\n\n  <dd>Every landing point in the book</dd>\n', 1)
        toc_p.write_text(toc, encoding='utf-8')

def main():
    rows = collect()
    if '--check' in sys.argv:
        for r in rows: print(f"{r['page']:>4}  {r['file'].split('/')[-1]:45} {r['id']:28} {r['incipit']}  — {r['prayer']}")
        print(len(rows), 'jewels'); return
    OUT.write_text(render(rows), encoding='utf-8')
    register()
    print(f'{len(rows)} jewels -> {OUT.relative_to(SRC.parent)}; spine/NCX/TOC page registered')

if __name__ == '__main__':
    main()
